kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kube-backup-reader
rules:
- apiGroups: ["*"]
  resources: [
    "configmaps",
    "cronjobs",
    "deployments",
    "daemonsets",
    "ingresses",
    "namespaces",
    "networkpolicies",
    "replicationcontrollers",
    "services",
    "secrets",
    "statefulsets",
    "storageclasses",
    "customresourcedefinitions"
  ]
  verbs: ["get", "list"]