apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: default
    namespace: ''
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    name: kube-public
    namespace: ''
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
- apiVersion: v1
  kind: Namespace
  metadata:
    annotations: {}
    name: kube-system
    namespace: ''
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
kind: List
metadata:
  resourceVersion: ''
  selfLink: ''
