apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: glbc
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: GLBCDefaultBackend
  name: default-http-backend
  namespace: kube-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 30502
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: glbc
  sessionAffinity: None
  type: NodePort
