apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: kube-backup
  name: kube-state-backup
  namespace: kube-system
spec:
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: kube-backup
          name: kube-backup
        spec:
          containers:
          - env:
            - name: GIT_REPO
              value: git@github.com:jinjhuang/kube-backup.git
            - name: RESOURCETYPES
              value: ingress deployment configmap svc rc ds thirdpartyresource networkpolicy
                statefulset storageclass cronjob
            image: ptlange/kube-backup:1.9.3-2
            imagePullPolicy: Always
            name: backup
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /backup/
              name: cache
            - mountPath: /backup/.ssh
              name: sshkey
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: kube-backup
          serviceAccountName: kube-backup
          terminationGracePeriodSeconds: 30
          volumes:
          - name: sshkey
            secret:
              defaultMode: 420
              secretName: kube-backup-ssh
          - emptyDir: {}
            name: cache
  schedule: '*/10 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
